---
title: "ESM_201_A_2"
output: html_notebook
---



```{r}

# attach packages
library(tidyverse)
library(janitor)

grains <- read_csv("grain_2020.csv") %>% 
  clean_names()
  
##

ggplot(data = grains, aes(x = year, y = yield)) + 
         geom_line(aes(color = commodity)) +
  facet_wrap(~ commodity, scales = "free") +
  labs(x = "Years", y = "Yield (Bushels per hectare)", title = "Crop Yields by Time", caption = "Figure 1: Graph of crop yields \n (Bushels per hectare) of Barley, Corn, Oats, and Sorghum by time") +
  theme(plot.caption = element_text(hjust = 0))

  


```


#1b)

According to the graphs, it looks as if Barley and Corn have exponential growth. However, Oats and Sorghum have logistic growth.


#2a)

```{r}

fert <- read_csv("fertilizer_2020.csv") %>% 
  clean_names()
  
##

ggplot(data = fert, aes(x = year, y = kg_h)) + 
         geom_line(aes(color = fertilizer)) +
  facet_wrap(~ crop, scales = "free", nrow = 3) +
  labs(x = "Years", y = "Fertilizer Use (kilogram per hectare)", title = "Fertilizer Use by Time", caption = "Figure 2: Graph of fertilizer Use (kilogram per hectare) \n of Wheat, Soybeans, and Corn by time") +
  theme(plot.caption = element_text(hjust = 0)) +
   scale_x_continuous(limits = c(1967, 2006))

```


